version: '3.7'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-5.2-latest
    ports:
      - "10051:10051"
    ulimits:
     nproc: 65535
     nofile:
      soft: 20000
      hard: 40000
    deploy:
     mode: replicated
     replicas: 1
     resources:
      limits:
        cpus: '0.50'
    env_file:
     - .env_db_mysql
    secrets:
     - MYSQL_USER
     - MYSQL_PASSWORD
     - MYSQL_ROOT_PASSWORD
    depends_on:
     - mysql-server
    networks:
     zbx_net_backend:
       aliases:
        - zabbix-server
        - zabbix-server-mysql
        - zabbix-server-alpine-mysql
        - zabbix-server-mysql-alpine
    sysctls:
     - net.ipv4.ip_local_port_range=1024 65000
     - net.ipv4.conf.all.accept_redirects=0
     - net.ipv4.conf.all.secure_redirects=0
     - net.ipv4.conf.all.send_redirects=0
    labels:
     com.zabbix.description: "Zabbix server with MySQL database support"
     com.zabbix.company: "Zabbix LLC"
     com.zabbix.component: "zabbix-server"
     com.zabbix.dbtype: "mysql"
     com.zabbix.os: "alpine"
    
  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-5.2-latest
    ports:
     - "80:8080"
    deploy:
     mode: replicated
     replicas: 1
     resources:
      limits:
        cpus: '0.50'
    env_file:
     - .env_db_mysql
    secrets:
     - MYSQL_USER
     - MYSQL_PASSWORD
     - MYSQL_ROOT_PASSWORD
    depends_on:
     - mysql-server
     - zabbix-server
    healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:8080/"]
     interval: 10s
     timeout: 5s
     retries: 3
     start_period: 30s
    networks:
     zbx_net_backend:
      aliases:
       - zabbix-web-nginx-mysql
       - zabbix-web-nginx-alpine-mysql
       - zabbix-web-nginx-mysql-alpine
     zbx_net_frontend:
    stop_grace_period: 10s
    sysctls:
     - net.core.somaxconn=65535
    labels:
     com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
     com.zabbix.company: "Zabbix LLC"
     com.zabbix.component: "zabbix-frontend"
     com.zabbix.webserver: "nginx"
     com.zabbix.dbtype: "mysql"
     com.zabbix.os: "alpine"
    
  mysql-server:
    image: mysql:8.0
    command:
     - mysqld
     - --character-set-server=utf8
     - --collation-server=utf8_bin
     - --default-authentication-plugin=mysql_native_password
     - --performance-schema=FALSE
    volumes:
     - mysql-db:/var/lib/mysql
    deploy:
     mode: replicated
     replicas: 1
     placement:
        constraints:
          - node.labels.node1==true
     resources:
      limits:
        cpus: '0.50'
    env_file:
     - .env_db_mysql
    secrets:
     - MYSQL_USER
     - MYSQL_PASSWORD
     - MYSQL_ROOT_PASSWORD
    stop_grace_period: 1m
    networks:
     zbx_net_backend:
      aliases:
       - mysql-server
       - zabbix-database
       - mysql-database

networks:
  zbx_net_frontend:
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: "false"

  zbx_net_backend:
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: "false"

volumes:
  mysql-db:

secrets:
  MYSQL_USER:
    file: secrets/.MYSQL_USER
  MYSQL_PASSWORD:
    file: secrets/.MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: secrets/.MYSQL_ROOT_PASSWORD