
-- Generated by ORDS REST Data Services 19.4.6.r1421859
-- Schema: WKSP_TOMSOZOLINS  Date: Mon Mar 29 06:18:10 2021 
--

BEGIN
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'geo',
      p_base_path      => '/geo/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'geo',
      p_pattern        => 'geojson',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'geo',
      p_pattern        => 'geojson',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'declare
 total_rows number;
 counter pls_integer := 0;
 geopoint clob;
 cursor geopoints is
   select HOST_TYPE, HOST_MODEL, HOSTID, VENDOR, HOST_NAME, LOCATION_LON, LOCATION_LAT
  from GEOMAP;

begin
SELECT count(*) INTO total_rows from GEOMAP;
htp.prn(''{"type":"FeatureCollection","features":['');

for c in geopoints loop
    counter := counter + 1;
    geopoint := ''{"type":"Feature","properties":{'' || 
    ''"host_type":"'' || c.HOST_TYPE ||
    ''","host_model":"'' || c.HOST_MODEL ||
    ''","hostid":'' || c.HOSTID || 
    '',"vendor":"'' || c.VENDOR || 
    ''","host_name":"'' || c.HOST_NAME || 
    ''"},"geometry":{"type":"Point","coordinates":['' || c.LOCATION_LON || '','' || c.LOCATION_LAT || '']}}'';
    
    if counter < total_rows then
    htp.prn(geopoint || '','');
    else 
    htp.prn(geopoint);
    end if;

end loop;

htp.prn('']}'');

end;');

    
        
COMMIT;

END;