
-- Generated by ORDS REST Data Services 19.4.6.r1421859
-- Schema: WKSP_TOMSOZOLINS  Date: Mon Mar 29 06:19:11 2021 
--

DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'geo.api',
      p_base_path      => '/geoapi/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'geo.api',
      p_pattern        => 'delete',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'geo.api',
      p_pattern        => 'delete',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DELETE FROM GEOMAP');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'geo.api',
      p_pattern        => 'insert',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'geo.api',
      p_pattern        => 'insert',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
insert into GEOMAP(HOST_TYPE,HOST_MODEL,HOSTID,VENDOR,LOCATION_LAT,LOCATION_LON, HOST_NAME)
VALUES(:host_type, :host_model, :hostid, :vendor, :location_lat, :location_lon, :host_name);
end;
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'geo.api',
      p_pattern            => 'insert',
      p_method             => 'POST',
      p_name               => 'HOSTID',
      p_bind_variable_name => 'hostid',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'geo.api',
      p_pattern            => 'insert',
      p_method             => 'POST',
      p_name               => 'HOST_MODEL',
      p_bind_variable_name => 'host_model',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'geo.api',
      p_pattern            => 'insert',
      p_method             => 'POST',
      p_name               => 'HOST_NAME',
      p_bind_variable_name => 'host_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'geo.api',
      p_pattern            => 'insert',
      p_method             => 'POST',
      p_name               => 'HOST_TYPE',
      p_bind_variable_name => 'host_type',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'geo.api',
      p_pattern            => 'insert',
      p_method             => 'POST',
      p_name               => 'LOCATION_LAT',
      p_bind_variable_name => 'location_lat',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'geo.api',
      p_pattern            => 'insert',
      p_method             => 'POST',
      p_name               => 'LOCATION_LON',
      p_bind_variable_name => 'location_lon',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'geo.api',
      p_pattern            => 'insert',
      p_method             => 'POST',
      p_name               => 'VENDOR',
      p_bind_variable_name => 'vendor',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

    
    
  l_roles(1) := 'RESTful Services';
  l_modules(1) := 'geo.api';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'geomap',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'geomap',
      p_description    => '',
      p_comments       => NULL);  

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;                                    
        
COMMIT;

END;